version: '2.0'

pipelines:
  build_and_run_bot:
    trigger_mode: ON_EVERY_PUSH
    actions:
      - action: "Build and Run Telegram Bot"
        type: DOCKER
        image: python:3.10-slim
        working_directory: /app
        environment:
          - BOT_TOKEN: "7747598023:AAGfi-m_9gw2L_4McP6z62OjGlbc-AavNVY"
          - ADMIN_IDS: "1724246173"
          - OWNER_USERNAME: "BGMIDDOS1245"
        commands:
          - pip install python-telegram-bot
          - python raja.py
          
